name: "Chromatic Deployment"

# 워크플로우가 실행될 이벤트 설정
on:
  push:
    paths:
      - "apps/flower-house/**"

# List of jobs
jobs:
  test:
    # Operating System
    runs-on: ubuntu-latest
    # Job steps
    steps:
      - uses: actions/checkout@v1
      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies with pnpm
        run: pnpm install

      # 현재 디렉토리 확인 단계
      - name: Check current directory and list contents
        run: |
          echo "Current directory:"
          pwd
          echo "Directory contents:"
          ls -lah

      # Chromatic을 워크플로우 단계로 추가
      - uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          token: ${{ secrets.GITHUB_TOKEN }}
