name: Test Failure Workflow

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test_failure:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Run a failing step
        run: |
          echo "This step will fail"
          exit 1
      - name: Notify Slack on Failure
        if: failure()
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          PR_URL="${{ github.event.pull_request.html_url }}"
          PR_TITLE="${{ github.event.pull_request.title }}"
          PR_AUTHOR_LOGIN="${{ github.event.pull_request.user.login }}"

          declare -A author_slack_id=(
            [nakjun12]="U0768APFN0L" # 황낙준
          )

          read -r -d '' PAYLOAD << EOM
          {
            "blocks": [
              {
                "type": "header",
                "text": {
                  "type": "plain_text",
                  "text": "⚠️ GitHub Action 실패 알림",
                  "emoji": true
                }
              },
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "*PR 제목:* $PR_TITLE"
                }
              },
              {
                "type": "section",
                "fields": [
                  {
                    "type": "mrkdwn",
                    "text": "*PR 작성자:* <@${author_slack_id[$PR_AUTHOR_LOGIN]}>"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*PR 링크:* <$PR_URL|GitHub에서 보기>"
                  }
                ]
              },
              {
                "type": "divider"
              },
              {
                "type": "context",
                "elements": [
                  {
                    "type": "mrkdwn",
                    "text": "이 메시지는 자동으로 생성되었습니다. 문제가 있다면 개발팀에 문의해주세요."
                  }
                ]
              }
            ]
          }
          EOM

          # Send the message to Slack
          curl -X POST -H 'Content-type: application/json' --data "$PAYLOAD" $SLACK_WEBHOOK_URL
