name: Test Failure Workflow

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test_failure:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Run a failing step
        run: |
          echo "This step will fail"
          exit 1

  notify-on-failure:
    name: Notify Slack on Workflow Failure
    needs: [test_failure]
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - name: Notify Slack
        env:
          SLACK_WEBHOOK_URL: ${{secrets.SLACK_WEBHOOK_URL}}
        run: |
          PR_URL="${{ github.event.pull_request.html_url }}"
          PR_TITLE="${{ github.event.pull_request.title }}"
          PR_AUTHOR_LOGIN="${{ github.event.pull_request.user.login }}"

          declare -A author_slack_id=(
            [Siwon-medi]="US6EHTXN0"
            [Bigstar1108]="U04BBKYDHHV"
            [kimyumi1]="U06FSQ3DME3"
            [Spandyandy]="U0750BH1RS4"
            [nakjun12]="U0768APFN0L"
            [halswla]="U07E5UU7G9H"
          )
          # Build the message
          MESSAGE="Github Action이 실패했습니다. \n\n*PR 링크:* $PR_URL\n*PR 제목:* $PR_TITLE\n*PR 작성자:*  <@${author_slack_id[$PR_AUTHOR_LOGIN]}>\n "
          FAILURE_STEP="${{ toJson(steps) }}"

          MESSAGE="Github Action 워크플로우가 실패했습니다. :crown-sw:
          *PR:* <$PR_URL|$PR_TITLE>
          *작성자:* $PR_AUTHOR
          *실패 원인:* \`\`\`$FAILURE_STEP\`\`\`"

          curl -X POST -H 'Content-type: application/json' \
            --data "{\"text\": \"$MESSAGE\"}" $SLACK_WEBHOOK_URL
