name: Test Failure Workflow

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test_failure:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Run a failing step
        run: |
          echo "This step will fail"
          exit 1
      - name: Notify Slack on Failure
        if: failure()
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          PR_URL="${{ github.event.pull_request.html_url }}"
          PR_TITLE="${{ github.event.pull_request.title }}"
          PR_AUTHOR_LOGIN="${{ github.event.pull_request.user.login }}"

          declare -A author_slack_id=(
            [Siwon-medi]="US6EHTXN0"
            [Bigstar1108]="U04BBKYDHHV"
            [kimyumi1]="U06FSQ3DME3"
            [Spandyandy]="U0750BH1RS4"
            [nakjun12]="U0768APFN0L"
            [halswla]="U07E5UU7G9H"
          )
           # Build the message
          MESSAGE="Github Action이 실패했습니다. \n\n*PR 링크:* $PR_URL\n*PR 제목:* $PR_TITLE\n*PR 작성자:*  <@${author_slack_id[$PR_AUTHOR_LOGIN]}>\n "

          # Send the message to Slack
          curl -X POST -H 'Content-type: application/json' --data "{\"text\": \"$MESSAGE\"}" $SLACK_WEBHOOK_URL

          MESSAGE="Github Action 연결 테스트입니다. 확인하는 용도입니다:\n\n<@US6EHTXN0>\n<@U04BBKYDHHV>\n<@U06FSQ3DME3>\n<@U0750BH1RS4>\n<@U0768APFN0L>\n<@U07E5UU7G9H>\n\n모두 이 메시지를 확인하셨다면 답변 부탁드립니다."

          # Send the message to Slack
          curl -X POST -H 'Content-type: application/json' --data "{\"text\": \"$MESSAGE\"}" $SLACK_WEBHOOK_URL
