name: Test Failure Workflow

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test_job:
    runs-on: ubuntu-latest
    outputs:
      failure_reason: ${{ steps.set_failure.outputs.failure_reason }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Run a failing step
        id: failing_step
        run: |
          echo "This step will fail"
          exit 1  # 이 줄을 추가하여 실제로 실패하도록 합니다.
        continue-on-error: true

      - name: Set failure reason
        id: set_failure
        if: steps.failing_step.outcome == 'failure'
        run: |
          echo "failure_reason=Step 'Run a failing step' failed with exit code ${{ steps.failing_step }}" >> $GITHUB_OUTPUT

      - name: Fail the job if the failing step failed
        if: steps.failing_step.outcome == 'failure'
        run: exit 1

  notify-on-failure:
    name: Notify Slack on Job Failure
    needs: [test_job]
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - name: Notify Slack
        env:
          SLACK_WEBHOOK_URL: ${{secrets.SLACK_WEBHOOK_URL}}
        run: |
          PR_URL="${{ github.event.pull_request.html_url }}"
          PR_TITLE="${{ github.event.pull_request.title }}"
          PR_AUTHOR_LOGIN="${{ github.event.pull_request.user.login }}"

          FAILURE_REASON="${{ needs.test_job.outputs.failure_reason }}"

          declare -A author_slack_id=(
            [Siwon-medi]="US6EHTXN0"
            [Bigstar1108]="U04BBKYDHHV"
            [kimyumi1]="U06FSQ3DME3"
            [Spandyandy]="U0750BH1RS4"
            [nakjun12]="U0768APFN0L"
            [halswla]="U07E5UU7G9H"
          )

          AUTHOR_MENTION="<@${author_slack_id[$PR_AUTHOR_LOGIN]:-$PR_AUTHOR_LOGIN}>"

          # Build the message
          MESSAGE="Github Action 워크플로우가 실패했습니다. :crown-sw:
          *PR:* <$PR_URL|$PR_TITLE>
          *작성자:* $AUTHOR_MENTION
          *실패 원인:* $FAILURE_REASON
          *워크플로우 실행 URL:* ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"

          curl -X POST -H 'Content-type: application/json' \
            --data "{\"text\": \"$MESSAGE\"}" $SLACK_WEBHOOK_URL
