name: Update PR Description

on:
  pull_request:
    types: [opened, synchronize, edited]

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  update-pr-description:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get changed files, packages, and commits
        id: changes
        run: |
          # Get changed files
          CHANGED_FILES=$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} | sort)
          echo "Changed files:"
          echo "$CHANGED_FILES"

          # Function to find the nearest package.json or parent directory name
          find_package() {
            local dir=$(dirname "$1")
            while [[ "$dir" != "." && "$dir" != "/" ]]; do
              if [[ -f "$dir/package.json" ]]; then
                echo $(jq -r .name "$dir/package.json")
                return 0
              fi
              dir=$(dirname "$dir")
            done

              if [[ -f "./package.json" ]]; then
                echo $(jq -r .name "./package.json")
                return 0
              fi

            echo "Unknown"
          }

          # Get package names
          CHANGED_PACKAGES=$(echo "$CHANGED_FILES" | while read file; do find_package "$file"; done | sort | uniq)
          if [ -z "$CHANGED_PACKAGES" ]; then
            CHANGED_PACKAGES="No packages detected"
          fi
          echo "Changed packages:"
          echo "$CHANGED_PACKAGES"

          # Get all commit messages
          COMMIT_MESSAGES=$(git log --format="- %s%n%b" ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }} | sed -e '/^$/d' -e '/^- $/d')
          echo "Commit messages:"
          echo "$COMMIT_MESSAGES"

          # Set outputs
          echo "changed_files<<EOF" >> $GITHUB_OUTPUT
          echo "$CHANGED_FILES" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

          echo "changed_packages<<EOF" >> $GITHUB_OUTPUT
          echo "$CHANGED_PACKAGES" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

          echo "commit_messages<<EOF" >> $GITHUB_OUTPUT
          echo "$COMMIT_MESSAGES" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Fetch Open Issues for PR Creator
        id: open_issues
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ORG: "my-type-world-cup"
          REPO: "my-type-world-cup-frontend"
        run: |
          PR_CREATOR=$(gh pr view ${{ github.event.pull_request.number }} --json author --jq .author.login)
          OPEN_ISSUES=$(gh api graphql -f query='
            query($org: String!, $repo: String!, $creator: String!) {
              repository(owner: $org, name: $repo) {
                issues(states: OPEN, first: 20, filterBy: {assignee: $creator}) {
                  nodes {
                    number
                    title
                    url
                  }
                }
              }
            }
          ' -F org=$ORG -F repo=$REPO -F creator=$PR_CREATOR --jq '.data.repository.issues.nodes[] | "- [ ] \(env.ORG)/\(env.REPO)#\(.number) \(.title)"')

          echo "open_issues<<EOF" >> $GITHUB_OUTPUT
          echo "$OPEN_ISSUES" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Update PR Description
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: |
          # Prepare the new PR description
          NEW_DESCRIPTION=$'## 🤖 자동 생성된 PR 정보\n\n'
          NEW_DESCRIPTION+=$'### 📦 변경된 패키지\n'
          if [ "${{ steps.changes.outputs.changed_packages }}" == "No packages detected" ]; then
            NEW_DESCRIPTION+=$'패키지 변경 없음\n'
          else
            NEW_DESCRIPTION+=$(echo "${{ steps.changes.outputs.changed_packages }}" | sed 's/^/- /' | sed 's/*/-/g')
          fi

          NEW_DESCRIPTION+=$'\n### 📄 변경된 파일\n'
          NEW_DESCRIPTION+=$(echo "${{ steps.changes.outputs.changed_files }}" | sed 's/^/- /' | sed 's/*/-/g')

          NEW_DESCRIPTION+=$'\n\n### 📝 커밋 내역\n'
          NEW_DESCRIPTION+=$(echo "${{ steps.changes.outputs.commit_messages }}" | sed 's/^/- /')

          NEW_DESCRIPTION+=$'\n\n### 관련 이슈\n'
          NEW_DESCRIPTION+=$'아래 목록에서 이 PR과 관련된 이슈를 선택해주세요. 선택한 이슈는 자동으로 PR과 연결됩니다:\n\n'
          NEW_DESCRIPTION+=$(echo "${{ steps.open_issues.outputs.open_issues }}")

          # Update the PR description
          gh pr edit $PR_NUMBER --body "${NEW_DESCRIPTION}"

      - name: Link Issues to PR
        if: github.event.action == 'edited' && github.event.changes.body
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: |
          # Check if the comment is on a PR
          if ! gh pr view $PR_NUMBER &> /dev/null; then
            echo "This is not a PR. Skipping."
            exit 0
          fi

          # Get the current PR description
          PR_BODY=$(gh pr view $PR_NUMBER --json body -q .body)

          # Extract the issue section
          ISSUE_SECTION=$(echo "$PR_BODY" | sed -n '/^### 관련 이슈/,$p')

          # Find checked issues (now includes org/repo)
          CHECKED_ISSUES=$(echo "$ISSUE_SECTION" | grep -oP "(?<=- \[x\] )[a-zA-Z0-9-]+/[a-zA-Z0-9-]+#\d+")

          # Unlink previously linked issues
          CURRENT_LINKED_ISSUES=$(gh pr view $PR_NUMBER --json projectItems --jq '.projectItems[].content.title')
          for ISSUE in $CURRENT_LINKED_ISSUES
          do
            gh pr edit $PR_NUMBER --remove-project "$ISSUE"
            echo "Unlinked issue $ISSUE from PR #$PR_NUMBER"
          done

          # Link newly checked issues to PR
          for ISSUE in $CHECKED_ISSUES
          do
            gh pr edit $PR_NUMBER --add-project "$ISSUE"
            echo "Linked issue $ISSUE to PR #$PR_NUMBER"
          done

          # Update PR description to reflect linked issues
          UPDATED_ISSUE_SECTION=$(echo "$ISSUE_SECTION" | sed -E "s/- \[x\] ([a-zA-Z0-9-]+\/[a-zA-Z0-9-]+#[0-9]+)/- [x] \1 (연결됨)/g")
          UPDATED_PR_BODY="${PR_BODY//$ISSUE_SECTION/$UPDATED_ISSUE_SECTION}"

          gh pr edit $PR_NUMBER --body "$UPDATED_PR_BODY"
